[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.139.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/thank-you"
  to = "/thank-you/"
  status = 301
