backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
site_url: https://pixelbooth.netlify.app/
display_url: https://pixelbooth.netlify.app/
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/galleries'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: galleries/{{slug}}
    editor:
      preview: true
    fields:
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DDTHH:mm:ssZ' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
